# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: constructions-incongrues/jomayeux

site_url: https://jomayeux.incongru.org

publish_mode: editorial_workflow
media_folder: assets/uploads

collections: # A list of collections the CMS should be able to edit
  - name: 'episodes' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Episodes' # Used in the UI
    label_singular: 'Episonde' # Used in the UI, ie: "New Post"
    folder: '_episodes'
    slug: '{{slug}}'
    summary: '{{title}} -- {{year}}/{{month}}/{{day}}'
    create: true # Allow users to create new documents in this collection
    sortable_fields:
      - title
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Drafts
        field: draft
    fields: # The fields each document in this collection have
      - { label: 'Title', name: 'title', widget: 'number', tagname: 'h1' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY-MM-DD HH:mm',
          default: '{{now}}',
        }
      - label: 'Cover Image'
        name: 'image'
        widget: 'image'
        required: false
      - { label: 'Body', name: 'body', widget: 'markdown', hint: 'Main content goes here.' }

