# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: constructions-incongrues/jomayeux

site_url: https://jomayeux.incongru.org

media_folder: assets/uploads

collections: # A list of collections the CMS should be able to edit
  - name: 'episodes' # Used in routes, ie.: /admin/collections/:slug/edit
    label: 'Episodes' # Used in the UI
    label_singular: 'Episode' # Used in the UI, ie: "New Post"
    folder: 'episodes' # The folder where documents are stored
    slug: '{{slug}}'
    summary: '{{number}}'
    create: true # Allow users to create new documents in this collection
    sortable_fields:
      - number
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Drafts
        field: draft
    fields: # The fields each document in this collection have
      - { label: 'Number', name: 'number', widget: 'number', hint: 'Episode number, e.g., 42' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
      - {
          label: 'Publish Date',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY-MM-DD HH:mm',
          default: '{{now}}',
        }
      - label: 'Cover Image'
        name: 'image'
        widget: 'image'
        required: false

      - label: 'Body'
        name: 'body'
        widget: 'markdown'
        required: false
        hint: 'Main content goes here.'

